### ISSUE TITLE
[Remoto] Desenvolvedora Golang na RD Station

### ISSUE THREAD

**Issue by Beatrizvianabernardino** [wwgsampa/vagas#1]
## Nossa empresa

🚀 Somos uma das maiores empresas SaaS do Brasil. Desenvolvemos uma plataforma 100% brasileira de automação de marketing digital e vendas;

🌎 Temos desafios de expansão nacional (onde somos líderes) e de penetração internacional na América Latina e Europa. Atendemos + 25.000 clientes de todos os portes em +20 países;

⭐ As +650 pessoas do nosso time (RDoers, como chamamos por aqui) nos elegeram 7 vezes uma das melhores empresas para se trabalhar no país e nos deram 4.5 estrelas no Glassdoor.

👩 Valorizamos e apoiamos a profissional mulher e mãe: somos a 7ª melhor empresa para mulheres trabalharem no país (ranking GPTW) e temos um grupo de empoderamento feminino, como o SER e o Tech Ladies.

## Descrição da vaga

O desafio de nossa área de Engenharia está ligado à escala & performance, por isso estamos focados na evolução da nossa plataforma no tripé de infraestrutura (Kubernetes), dados (100% na GCP) e APIs (internas e externas) — e não vamos medir esforços pra isso! Para 2021 já dedicamos R$ 100.000 milhões em tecnologia e aquisição de novos negócios que complementem nossa visão de plataforma, e colocaremos ainda mais grana se tivermos boas oportunidades na mesa.

Dentro do seu squad, você contará com o apoio de pessoas na posição de Team Leader, Product Manager, Designer e Developer, além de toda a galera dos chapters, guildas e tribos pra te ajudar a tracionar suas entregas como Software Engineer!

**Suas principais entregas:**
- Desenvolver novas features para as soluções principalmente em Ruby e Go (conheça todas as nossas linguagens aqui);
- Participar do discovery técnico de novas features, trazendo a visão de engenharia para a solução proposta;
- Executar e medir experimentos no cenário de desenvolvimento em alguns projetos; 
- Seguir nossos princípios de Engenharia (Loose Coupling, High Cohesion; Design your code to be easier to understand, not easier to write; Reducing global complexity is more important than reducing local complexity; Automate Everything).

## Local

Remoto 

## Requisitos

**Obrigatórios:**
- Se identifica como uma mulher, (se você não atende esse requisito, sua vaga é esta aqui);
- Experiência com desenvolvimento backend em qualquer stack, preferencialmente com Ruby, Go, Java, Elixir, Python ou Javascript.
- Vivência com boas práticas de desenvolvimento, como Clean Architectures ou TDD, BDD, DDD e entre outras;
 
**Diferenciais:**
- Experiência com metodologias ágeis de entrega, Scrum ou Kanban;
- Conhecimento com autenticação e autorização;
- Boas noções de desenvolvimento em Ruby ou Go;
- Experiência com arquitetura em nuvem (AWS, GCP ou Azure);
- Ser (ou querer se tornar) uma pessoa ativa na comunidade, que compartilha conhecimento dentro e fora da empresa em eventos, artigos, mentorias, iniciativas voluntárias, projetos open source, etc.

## Benefícios

- Plano de saúde
- Seguro de vida
- VR ou VA
- Plano odontológico
- Auxílio Home Office

## Contratação

CLT

## Como se candidatar

Se cadastrar no link, clicando [aqui](https://grnh.se/0534dbf12us). 

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 5 dias após cada processo.
E-mail para contato em caso de não haver resposta: beatriz.viana@rdstation.com

#### Alocação
- Remoto

#### Regime
- CLT

#### Nível
- Júnior
- Pleno
- Sênior
- Especialista

**Comment by guibranco** [comment]
@Beatrizvianabernardino  Esta vaga ainda se encontra aberta ? Ou pode ser encerrada ?
